sudo: require
services:
- docker
before_install:
- docker pull node:8-onbuild
install:
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
- docker run --rm probot-hello npm run lint
deploy:
  provider: heroku
  api_key:
    secure: ctnO659ZOdMpLyQOzuj0JrIFOJi+eBey5CRnRmqlV3G6EE//vMHSYyPL5mXbLVq2vKpXptt7BLVGau/qzGccVfwk5eKVDr6qIPvW+OUVquWoTNpFlDyKK9ybu4W40dOWwp8hZ+wBIngfdZOJk70VxwHZsJMiEjAvsjUCxDOA98Y3FQyRWp3VR+GC9GDlWmMcPA3Qntl0xzRDcvObluVKXU155V+ucK6hnpnpCtN98MTp8gHHaE3IdaKbeiVrbCoVZvG/2sAolDLTdCU/1hXytPWpWPKBl2dbSSLtxpqL0r+RGrG+cSHLIRwL00CFyebd8M4iII18NfLd2l82UHIBgXYNZ82v9Nwi5nWJQlijiWPUw+3V+GWv2ZdG61N+BSuv+GWMZjQ68wYSYJdtNOJ45hdskJV54FuDCwk1zAtXqrtazy4EUOhqy1mTyeHrifa+8EY9YbGZqyt3+tht5B7cFrQjdymqUc4knryIeKWGBhKkr2WpQSEO/THtsxoV7JZs6UEGNEBrjz0iISFwtJHLy3Nifk0ityeHASCX3UEKKRfKaufslsIiKENc+6/iv6RJcsGN1f6QSe4ifQgnkMbD1y/Sj0M+V5AZcmFLYInRPJ8yJ/EZMQtEc7V3HXcD5azSM3loKdBd9FRVAYC0/37NFXiafJtG0cgi2e8QGWQrWuk=
  on: heroku_production
  app: probot-wenlockca
