sudo: require
services:
- docker
before_install:
- docker pull node:8-onbuild
install:
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
- docker run --rm probot-hello npm run lint
deploy:
  provider: heroku
  api_key:
    secure: d72oDb9hx9jc6TWo770qVvB3rv+OUD9n0TNhr6ulBCQ9CJRy/RTxGZ/oDy36vSOHvKwmyS/2BsZB/Aw+0WiJfOo+MmSwE+8KXsIbZINO2kCPHBLjc++Aiu2kav+Q6r1OoROj3sj+TeRZfSlhX7KTnhyCYumAAvLSK8m0ydwOnDYLic6tpx6pkHyPziuErY/iypBaUOVcWK8Jda8sTW6GYp70IRb8On/fG1bVk5An6hmRDwyXk2FJ1x/liwr0wy9hOySNlSlnq4xB6Q8IQt+cEeHR668TRqoJP2S1HnvaVdFoQLFBzlNkfklcWylK1nlmxgxVXb4/8DSKNcfyvlWek1fikKAEEQwXCzxlt8ucG4EQRH3JWPklDqJkMpMdyYJIWdVxMkMJbGlkUt3AUMxdeo89RJKDHlSr0nDJINF7gcqukZaSd94cB0FXazThKQBmrJ1C/DyGwxl5/OfGfg55hMIDUS0vaSHEwzE4N4hMunS2HShvNOU8D+13k2oL6D+0PvJ6xIy/7wFNinbl8BIsEs82ueayrHjWFJFBGqZhLwvAYN5A8MWzR1sJSWL2erY0hHmUjRN0zXrTI+zLvD6K9zeN2CNTfokm2UVw27dw6R3CzdO+e7DR44zrfM4uT5VF04ZpR0xmguzJV41+/WDCqqkCmrwbQ35hcGIh4yBRvUM=
  on: heroku_production
  app: probot-wenlockca
